# config.yaml
input_files:
  custom_genes: "datasets/Custom_genes_analysis/custom_genes.txt"
  deg_csv: "datasets/RNAseq/stringtiefile/RNA_A_vs_RNA_N_DEG.csv"
# === File paths configuration ===
paths:
  dir: "datasets/Custom_genes_analysis"
  scripts_dir: "scripts/snakemake/Custom_genes_analysis/"

  jaspar_dir: "datasets/JASPAR2026_CORE"
  tf_mapping_file: "datasets/Ath_TF_list.txt"

params:
  log2fc_up: 1
  log2fc_down: -1

  padj: 0.05
